language: node_js
node_js:
- '12'
before_install:
  - npm i -g npm@6.9.0
script: ng run gameshow:build:production --progress=false
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: ZCPIgJFqLvuNMw4UiUjWBWzZQCiy++Q0T97+PELtSfhdkmQ24D8lepuV6N9JBctbucnPJ4SOVTF1SCnPEOct6B6o07TYWrC1Zwp91kpHPU/Zw9OZ7PRLuP9LhtexGPySRNdRJ5VEchWc7O/2hnpkJEHtb+1eRA1c//f5BDgXTApydsd9zG7NhBKLzEoPZ2mTxMgQnK3PpJrPAmH6Fx517/3aySxMdOB3gLKgse19Sa/lb700zJLsxO9EVOkzPd39xOfOV5XVVDVpkEs8xKh7y/faTXnNlCnmHu61nkTEz7CUwXJoJraIs/YZJ6r6mv+3TXXrYRVUSoe/UyhPClOHvcgmgKDkYPUchfkpebQnYUJhIHaQs9dQTjrK+CL2FR925IfqUqpWegy5HhHTvaZZT/J4IR0rzYOsBSEEMhVy4LYvdvyeZucPID+mY8XFsu6CFJAL1+gvxeIRVs/GWBdOToxtmPKFehdesP5GpdEiUSPJDOGsmDWiOPLo+gLqkHEV8aZSviTI14L0SLzwNlHmLo/TLksPQ78kHl6hh9K9ObtPZvbEZvZNPmu3I1KhyE64wavoPOJA3K2KUP+dAvZ+o6NsWlio+Hvi8+ndrQ6qEoKWcVFjaYivjUvMhpIlJXPL/b8UhlcSje7Sw/83Rl37PQ8MovMMRq8K5u5tZJSBKPY=
notifications:
  email:
    on_success: always
    on_failure: always
